go:-
hypothesis(Disease),
write('-----------------------------------------'),
nl,
write('The person may have : '),
write(Disease),
nl,
write('-----------------------------------------'),
nl,
write('Its Better to consult a Nephrologists or Oncologists'),
undo.

hypothesis(chronickidneydisease) :- chronickidneydisease,!.
hypothesis(kidneystone) :- kidneystone,!.
hypothesis(acutekidneyinjury) :- acutekidneyinjury,!.
hypothesis(kidneycancer) :- kidneycancer,!.
hypothesis(kidneycysts) :- kidneycysts,!.
hypothesis(unknown).

kidneystone:-
verify(pain_in_the_abdomen),
verify(pain_in_the_lowerback),
verify(blood_in_urine),
verify(fever),
verify(nausea),
verify(frequent_urination),
write('KIDNEYSTONE'),
nl,
write('Presence of stones in the kidney due to a decrease in urine volume or excess of stone-forming substances in the urine'),
nl,
write('TESTS AND SCANS'),
nl,
write('1:Blood Test'),
nl,
write('2:Urine Test'),
nl,
write('3:X-ray'),
nl,
write('4:CT scan'),
nl,
write('5:Ultrasound'),
nl,
write('COMPLICATIONS OF KIDNEY STONE'),
nl,
write('1.Recurrence - the most common complication is that the kidney stones can occur again'),
nl,
write('2.Obstruction and infection - Blockage of the urinary tract can cause kidney damage and also can make the urinary tract susceptible to infection.'),
nl,
write('ADVICES AND SUGGESTIONS:'),
nl,
write('Consult doctor and take medication'),
nl,
write('The medicine includes:'),
nl,
write('1.Analgesic-Helps to relieve pain'),
nl,
write('2.Antiemetic: Injected to treat nausea (feeling of sickness) or vomiting.'),
nl,
write('3.Alpha blockers/calcium channel blockers: Used as part of medical expulsive therapy to facilitate the passage of stones.'),
nl,
write('FOOD TO AVOID'),
nl,
write('1:Food rich in sodium'),
nl,
write('2:Food rich in oxalate'),
nl,
write('3.Avoid animal meat'),
nl,
write('FOOD TO EAT :calcium rich foods'),
nl,
write('Drink plenty of water'),
nl.

acutekidneyinjury:-
verify(swelling_of_bodyparts),
verify(fatigue),
verify(loss_of_appetite),
verify(nausea),
verify(chest_pain),
write('A condition when an abrupt reduction in kidneys ability to filter waste products occurs within a few hours or a few days'),
nl,
write('COMPLICATION OF ACUTEKIDNEYINJURY'),
nl,
write('1.Shortness of breath'),
nl,
write('2.Loss of kidney function'),
nl,
write('3.Muscle weakness'),
nl,
write('TESTS AND SCANS TO TAKE:'),
nl,
write('1:Kidney Function Test'),
nl,
write('2:Kidney Biopsy'),
nl,
write('3:Ultrasound'),
nl,
write('ADVICES AND SUGGESTIONS:'),
nl,
write('Consult doctor and take medication'),
nl,
write('Take Intravenous Therapy'),
nl,
write('The medicines are:'),
nl,
write('1.Diuretics: To minimise the swelling for AKI caused by fluid buildup'),
nl,
write('2.Potassium lowering drugs: Prevent the accumulation of potassium in the blood'),
nl,
write('3.Dietary supplements: Calcium is given when the levels drop'),
nl,
write('FOOD TO AVOID:'),
nl,
write('1:Salty foods'),
nl,
write('2:Food rich in phosphorous'),
nl,
write('FOOD TO EAT:Moderate level of potassium foods'),
nl,
write('Drink plenty of water'),
nl.

kidneycancer:-
verify(blood_in_urine),
verify(sudden_weightloss),
verify(lumps_in_abdomen),
verify(fever),
verify(pain_in_lowerback),
verify(loss_of_appetite),
write('A disease caused by development of cancerous (malignant) cells in the kidney'),
nl,
write('COMPLICATIONS OF KIDNEY CANCER'),
nl,
write('1.Metastasis'),
nl,
write('2.Liver dysfunction'),
nl,
write('3.Elevated levels of red blood cells'),
nl,
write('TESTS AND SCANS:'),
nl,
write('1:Blood Test'),
nl,
write('2:Kidney Biopsy'),
nl,
write('3:MRI'),
nl,
write('4:CT scan'),
nl,
write('ADVICES AND SUGGESTIONS:'),
nl,
write('Consult doctor and take medication'),
nl,
write('Take Radiation therapy'),
nl,
write('The medicine include:'),
nl,
write('1.Immunotherapy: This is a biological therapy, which uses the immune system to fight against cancer.
'),
nl,
write('2.Targeted therapy: These medications identify and control the abnormal multiplication of cancer cells.
'),
nl,
write('FOOD TO AVOID'),
nl,
write('1:Food rich in oxalate'),
nl,
write('2.Avoid animal meat'),
nl,
write('FOOD TO EAT:Foods high in calories'),
nl,
write('Drink plenty of water'),
nl.

kidneycysts:-
verify(abdominal_pain),
verify(abdominal_swelling),
verify(fever),
verify(frequent_urination),
verify(backpain),
verify(high_blood_pressure),
write('A condition characterised by small, oval or round thin-walled sacs with watery fluid in the kidney'),
nl,
write('COMPLICATIONS OF KIDNEY CYSTS'),
nl,
write('1.Cyst infection.'),
nl,
write('2.A ruptured cyst causing severe pain.'),
nl,
write('3.Hydronephrosis – urine obstruction causes kidney swelling'),
nl,
write('TESTS AND SCANS:'),
nl,
write('1:Ultrasound Test'),
nl,
write('2:MRI'),
nl,
write('3:CT scan'),
nl,
write('ADVICES AND SUGGESTIONS:'),
nl,
write('Consult doctor and take medication'),
nl,
write('Take Radiation therapy'),
nl,
write('FOOD TO AVOID'),
nl,
write('1:Food rich in oxalate'),
nl,
write('2:Avoid animal meat'),
nl,
write('FOOD TO EAT :Foods high in calories'),
nl,
write('Drink plenty of water'),
nl.

chronickidneydisease :-
verify(nausea),
verify(loss_of_appetite),
verify(swelling),
verify(hypertension),
verify(urinate_more),
verify(decreased_mental_sharpness),
verify(sleepingproblems),
verify(blood_in_urine),
verify(chestpain),
verify(shortness_of_breath),
verify(persistent_iching),
write('A condition characterised by a gradual loss of kidney function. Early stage'),
nl,
write('COMPLICATIONS OF CHRONIC KIDNEY DISEASE'),
nl,
write('1.Fluid retention: Kidney failure leads to fluid retention causing swelling in the arms and feet'),
nl,
write('2.Cardiovascular disease – Heart and blood vessels are affected due to kidney failure'),
nl,
write('3.Imbalance in potassium levels: This can be life-threatening'),
nl,
write('4.Decreased immune response'),
nl,
write('5.Impairing central nervous system'),
nl,
write('6.Complications in pregnancy'),
nl,
write('7.Complete loss of kidney function in the late stage'),
nl,
write('8.Imbalance in potassium levels: This can be life-threatening'),
nl,
write('TESTS AND SCANS:'),
nl,
write('1:Kidney Function Test'),
nl,
write('2:Urine Test'),
nl,
write('3:Ultrasound'),
nl,
write('4:Hormone Test'),
nl,
write('5:Kidney Biopsy'),
nl,
write('6:Renal flow scan'),
nl,
write('ADVICES AND SUGGESTIONS:'),
nl,
write('Visit doctor and take medications'),
nl,
write('FOOD TO EAT:'),
nl,
write('1:Consume low potassium foods like apples,cabbage,green beans,carrot and so on'),
nl,
write('3:Limit protien content.Eat low protien foods.'),
nl,
write('FOOD TO AVOID :'),
nl,
write('1:High Potassium foods'),
nl,
write('2: High protien foods'),
nl.

        ask(Question):-
        write('Does the patient have following symptom:'),
        write(Question),
        write('?'),
        read(Response),
        nl,
        ((Response == yes; Response == y)
->
    assert(yes(Question));
    assert(no(Question)),fail).

    :- dynamic yes/1,no/1.

        verify(S):-
        (yes(S)
        ->
        true;
        (no(S)
        ->
        fail;
        ask(S))).

undo:-retract(yes(_)),fail.
undo:-retract(no(_)),fail.
undo.




